### ISSUE TITLE
Setup automated (cron job) update of git-annex repository from the official repo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#1]
It should not be too frequent, e.g. every other hour or may be even 6 hours, so we do not overwhelm the CI etc

**Comment by jwodder** [comment]
@yarikoptic Where/how should this job be run?  On drogon or another system?  As a GitHub Actions workflow?

**Comment by yarikoptic** [comment]
I wondered myself, I think best would be a github actions here to have everything in a single place.

**Comment by jwodder** [comment]
@yarikoptic Should only the master branch be updated or all branches in the official repo?

**Comment by yarikoptic** [comment]
Probably just master, I don't think any other of direct interest ATM
