### ISSUE TITLE
Q: where to find the build logs?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#105]
https://github.com/datalad/git-annex#client-tests has bunch of red badges so it is needed to know how those jobs have failed. https://github.com/datalad/git-annex-ci-client-jobs/branches seems have no relevant branches which might contain build logs, https://github.com/datalad/git-annex/blob/master/clients/README.md has no hits for searching `log`.

I am even thinking may be we should 
- make https://github.com/datalad/git-annex-ci-client-jobs/branches private
- do push logs in per build branches;  have some branch or reference which points to the latest for each client/run
- make badges here point to those logs (now they just point to badge svg, not much use)

**Comment by jwodder** [comment]
@yarikoptic The logs are pushed to the `result-*` branches, where a GitHub Action uploads them as artifacts that are then also collected by tinuous in `/mnt/datasets/datalad/ci/git-annex-ci-client-jobs` on smaug.

**Comment by yarikoptic** [comment]
Ah, cool -- thanks!  

ATM I see  `builds/2022/03/push-result-s/handle-result.yaml-5-8ff806f4-success` where `success` is probably for the entire github CI run, which succeeded despite smaug failing underneath:

```
datalad@smaug:/mnt/datasets/datalad/ci/git-annex-ci-client-jobs/builds/2022/03/push-result-s/handle-result.yaml-5-8ff806f4-success/result-smaug-609$ tail git-annex.log
    required_content:                                     OK (3.54s)
    add subdirs:                                          OK (3.65s)
    addurl:                                               OK (2.20s)

3 out of 994 tests failed (1362.87s)
  (Failures above could be due to a bug in git-annex, or an incompatibility
   with utilities, such as git, installed on this system.)
+ cd /mnt/datasets/datalad/git-annex-build-client
+ chmod -R +w 609
+ rm -rf 609

```
- smaug's log filename doesn't reflect that it did fail -- should we reflect status there?
- shouldn't overall CI run also reflect status of individual clients (if any fail -- "failed")?

**Comment by jwodder** [comment]
@yarikoptic 

> smaug's log filename doesn't reflect that it did fail -- should we reflect status there?

The test exit codes are stored in the `.rc` files next to the `.log` files in the artifacts.

> shouldn't overall CI run also reflect status of individual clients (if any fail -- "failed")?

No, I think the CI status should reflect whether the CI post-processing succeeded in updating the badges and uploading the artifact.

**Comment by yarikoptic** [comment]
ok, thank you.
