### ISSUE TITLE
daily status email

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#109]
not sure if could/should be sent out by some github action or just some cronjob on smaug.  

`Subject: datalad/git-annex [OK X], [FAILED Y]`

and in the body just a printout in yaml of some record which would have github, and all the clients on the top level, and then individual workflows with OK/FAILED indicator for each of them.  Where present, would be nice to have them as URLs to corresponding action run, but I guess something would be better than nothing -- I just often forget to check current status and miss some change in the situation.

**Comment by jwodder** [comment]
@yarikoptic To be clear: By "clients", do you mean the Ubuntu/macOS/Windows workflows on GitHub Actions or the "local" clients on ndoli & smaug?

**Comment by yarikoptic** [comment]
the latter -- "local" clients on ndoli & smaug.

**Comment by jwodder** [comment]
@yarikoptic Then what exactly do you mean by "individual workflows" and "URLs to corresponding action run"?  The local clients' whole thing is that they're not run under GitHub Actions.

**Comment by yarikoptic** [comment]
> Then what exactly do you mean by "individual workflows" and "URLs to corresponding action run"?

<details>
<summary>workflows as you see them on Actions tab https://github.com/datalad/git-annex/actions</summary> 

![image](https://user-images.githubusercontent.com/39889/159810992-7dedd8d5-ecb2-4870-8cf7-7b72c2a62bd8.png)

</details>

so individual workflows like "Build git-annex on Ubuntu" and other "Build git-annex" ones.

Example
- FAIL [Build git-annex on Ubuntu](https://github.com/datalad/git-annex/actions/runs/2026054386) 2022-03-23T??:??
  - FAIL [build-package](https://github.com/datalad/git-annex/runs/5654301379?check_suite_focus=true) 2022-03-23T??:??
  - --- test-annex
  - --- test-annex-more
  - --- test-datalad
- ...

would correspond current unfortunate state which I wasn't aware about :-/

> The local clients' whole thing is that they're not run under GitHub Actions.

I know. But it shouldn't preclude getting their current/latest status, possibly with the date when it was updated

**Comment by jwodder** [comment]
@yarikoptic So is this e-mail supposed to cover the tests in GitHub Actions, on local clients, or both?  Could you give an example of a complete e-mail's contents?

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
- both

extended example [above](https://github.com/datalad/git-annex/issues/109#issuecomment-1076908664) with results for a local client etc
