### ISSUE TITLE
10.20220322 release failed to build on Ubuntu

### ISSUE THREAD

**Issue by jwodder** [datalad/git-annex#110]
See https://github.com/datalad/git-annex/runs/5648959425?check_suite_focus=true

**Comment by jwodder** [comment]
@yarikoptic This is still ongoing; all Ubuntu builds have failed since the release.

**Comment by yarikoptic** [comment]
indeed the same
```
dpkg-checkbuilddeps: error: Unmet build dependencies: libghc-http-client-restricted-dev
```
although I thought that e56e5d9d2aaa538ba62530bbc526ca53d7e9dbbb where I added installation of that dependency should have fixed it, and I think I saw the workflow for building the image to run but 
https://github.com/datalad/git-annex/actions/workflows/build-linux-buildenv.yaml?query=workflow%3A%22Build+git-annex+on+Ubuntu%22
lists no (recent) runs.  Will submit a PR to see explicitly what runs and fails etc

**Comment by yarikoptic** [comment]
I think changes introduced by #111 should have addressed it, I will close but we might need to reopen if next run would prove me wrong!

**Comment by yarikoptic** [comment]
ok, now

**Comment by yarikoptic** [comment]
We build again. I will just keep it without Deb for that release
