### ISSUE TITLE
"Trigger build workflows for active pull requests" workflow is constantly failing; delete it?

### ISSUE THREAD

**Issue by jwodder** [datalad/git-annex#141]
Almost every run of the [Trigger build workflows for active pull requests](https://github.com/datalad/git-annex/actions/workflows/build-prs.yml) for the past two days has failed because of a request to GitHub returning 502.  While we could add in request retrying in an attempt to work around this, I would prefer to get rid of the workflow entirely.  The only purpose of the workflow is to run PRs made against the mirror in `upstream/master` rather than against `master`, but there's no need to make such PRs now that we have the `patches/` directory.  For months now, the only times this workflow has done anything is when it's failed, and it's clearly outlived its usefulness.

**Comment by yarikoptic** [comment]
oh, I didn't even know that we had such functionality indeed, and remembered only about `patches/` approach which even though "more tedious" - but it is persistent in that then if merged those patches could be used, unlike the just "let's try" approach through PRs to `upstream/master`. I am ok to delete it . If we decide to reincarnate for some reason -- we know where to find it.
