### ISSUE TITLE
some missing step to make client (openmind) reported?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#155]
https://github.com/datalad/git-annex-ci-client-jobs/branches lists a number of builds for openmind but we neither have badge in https://github.com/datalad/git-annex-ci-client-jobs/tree/master/badges nor in README.md here.

I think I followed https://github.com/datalad/git-annex/tree/master/clients to its entirety, so there might be a step still missing being listed there or some automation did not kick in?

**Comment by jwodder** [comment]
@yarikoptic The fact that there are `build-openmind7-*` branches there but no `result-openmind7-*` branches indicates that the job isn't running properly on the client system (or that no job has completed on the client yet).  What exactly did you mention seeing [here](https://github.com/datalad/git-annex/issues/154#issuecomment-1431672426)?

**Comment by yarikoptic** [comment]
gotcha -- I just misunderstood workflow a little, reopened #154 , will finish setting up openmind (head node is overloaded, everything takes time so I keep loosing patience/switching to another task, apparently never finished setting up conda env for it ;-) )

**Comment by jwodder** [comment]
@yarikoptic The only `result-openmind7-*` branches I see listed there are ones whose "Process result" job failed due to multiple jobs trying to push to the `master` branch at the same time.  There have been several successfully-processed & deleted `result-openmind7-*` branches already, and I've seen them reported in the daily e-mail.

By "still not reported", do you simply mean that the badges aren't shown in the README?  That requires manual editing.

**Comment by yarikoptic** [comment]
right -- I meant README, I forgot that it is not automagically generated/updated. Please update it accordingly and add to clients/README.md the necessity for that step.

as for failed "process result". I guess we need to do in a loop with some `git merge` or there would be conflicts and thus we better just discard some or what should we do?

**Comment by jwodder** [comment]
@yarikoptic The "Process results" step that updates the repository is just updating the badge images to show the latest results; thus, if some other job beat us to updating the repository, it's likely that our badges are out of date and we should not bother retrying.

**Comment by yarikoptic** [comment]
let's consider this resolved by https://github.com/datalad/git-annex/pull/156 .
