### ISSUE TITLE
overall client status badge?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#157]
@jwodder Is it possible easily (e.g. while analyzing results cross clients) to deduce overall status of tests on clients -- passing or not, and have a badge provided from some branch/ref for that?

**Comment by jwodder** [comment]
@yarikoptic Yes, it should be easy.

**Comment by jwodder** [comment]
@yarikoptic What should the text on the left side of the badge say?  Just "Clients" or something more informative?

**Comment by yarikoptic** [comment]
May be "Tests on clients: " if "failing" , "passing".
