### ISSUE TITLE
Add to daily git-annex build/test status report appveyor

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#164]
@joeyh setup an appveyor build on https://ci.appveyor.com/project/mih/git-annex -- would be great to have it included into our daily mail/status reports.  Probably last after clients testing.

**Comment by jwodder** [comment]
@yarikoptic Exactly what do you want shown for Appveyor builds?

**Comment by yarikoptic** [comment]
the status with url for the builds for the past day, like we do for the builds we get done here or on clients.  In markdown (report is in HTML, colors different for PASS) to be like this for today: 

- Other builders
  - mih appveyor : [1.0.168](https://ci.appveyor.com/project/mih/git-annex/builds/47136512)
    - [PASS](https://ci.appveyor.com/project/mih/git-annex/builds/47136512/job/ke5nukvxwuwqsl8s) ID=WinP39core, APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2019, STACK_ROOT=c:\sr
    - [PASS](https://ci.appveyor.com/project/mih/git-annex/builds/47136512/job/8njaq6dlmqihnvto)  ID=MacP38core, APPVEYOR_BUILD_WORKER_IMAGE=macos-monterey

**Comment by jwodder** [comment]
@yarikoptic Do you want "PASS" next to each job to be a link, or do you want it to be green text?  Those are somewhat at odds.

**Comment by yarikoptic** [comment]
> @yarikoptic Do you want "PASS" next to each job to be a link, or do you want it to be green text? Those are somewhat at odds.

;-) indeed. the way you have done (can be seen on https://datalad.github.io/git-annex-ci-reports/) is good!
