### ISSUE TITLE
Add ability to patch in our build workflow

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#18]
we are growing into a distribution: It seems that we would benefit from being able to apply patches (eg from #16) until they are accepted upstream. Patches could just go under `patches/` directory, she's and applied in order. Smarter way could be to sense of first if patch might have already be applied upstream,  issue a PR to remove it (if not issued already, so probably by making/checking a branch like rmpatch-patchname) and skip it meanwhile. This would allow to apply patches and remove them knowingly.

**Comment by jwodder** [comment]
@yarikoptic If a patch fails to apply, should the build fail, or should the patch just be skipped?

> so probably by making/checking a branch like rmpatch-patchname

What if two different patches with the same name are created over the lifetime of the repository?

**Comment by yarikoptic** [comment]
if patch 
- reverse applies  cleanly -- skip and send a PR to have it removed
- fails to apply -- fail the build.
  - if there is a reasonable easy way to issue (without reissuing not sure if easy since there would be no branch to easily identify) a new issue showing output from `patch` -- that could help to react more quickly

> What if two different patches with the same name are created over the lifetime of the repository?

that is ok if previous one was removed already -- branch would be gone by then.
