### ISSUE TITLE
Experiencing issues 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#201]
recent builds got worse and worse
![image](https://github.com/datalad/git-annex/assets/39889/ed45f7e7-c5e8-411b-b776-15a64b014961)

<details><summary>and here is the most recent one in particular</summary>

GitHub:

FAIL [Build git-annex on Ubuntu #1457](https://github.com/datalad/git-annex/actions/runs/8368865637) 2024-03-21 02:35:15+00:00

PASS [build-package](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22913653008) 2024-03-21 03:02:01+00:00
PASS [test-annex-more](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915199796) 2024-03-21 03:56:44+00:00
FAIL [test-datalad (master)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915199902) 2024-03-21 03:56:43+00:00
PASS [test-annex (normal, ubuntu-latest)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915199986) 2024-03-21 03:56:43+00:00
FAIL [test-datalad (maint)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915200071) 2024-03-21 03:56:45+00:00
FAIL [test-datalad (release)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915200141) 2024-03-21 03:56:43+00:00
PASS [test-annex (crippled-tmp, ubuntu-latest)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915200204) 2024-03-21 03:56:43+00:00
PASS [test-annex (crippled-home, ubuntu-latest)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915200279) 2024-03-21 03:56:43+00:00
PASS [test-annex (nfs-home, ubuntu-latest)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915200374) 2024-03-21 03:56:42+00:00
PASS [test-annex (custom-config1, ubuntu-latest)](https://github.com/datalad/git-annex/actions/runs/8368865637/job/22915200459) 2024-03-21 03:56:43+00:00
FAIL [Build git-annex on macOS #1440](https://github.com/datalad/git-annex/actions/runs/8368599357) 2024-03-21 02:04:31+00:00

PASS [build-package](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22912952790) 2024-03-21 02:04:42+00:00
PASS [test-annex-more](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913254071) 2024-03-21 03:09:40+00:00
PASS [test-annex (normal, macos-11)](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913254227) 2024-03-21 03:09:17+00:00
FAIL [test-datalad (master)](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913254408) 2024-03-21 03:12:14+00:00
PASS [test-annex (crippled-tmp, macos-11)](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913254518) 2024-03-21 03:01:48+00:00
FAIL [test-datalad (maint)](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913254679) 2024-03-21 03:12:05+00:00
PASS [test-annex (custom-config1, macos-11)](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913254823) 2024-03-21 03:01:56+00:00
FAIL [test-datalad (release)](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913254927) 2024-03-21 03:19:29+00:00
PASS [test-annex (normal, macos-latest)](https://github.com/datalad/git-annex/actions/runs/8368599357/job/22913255035) 2024-03-21 02:33:59+00:00
FAIL [Build git-annex on Windows #1395](https://github.com/datalad/git-annex/actions/runs/8369275314) 2024-03-21 03:31:07+00:00

PASS [build-package](https://github.com/datalad/git-annex/actions/runs/8369275314/job/22914750514) 2024-03-21 03:31:15+00:00
PASS [test-annex (normal, windows-2019)](https://github.com/datalad/git-annex/actions/runs/8369275314/job/22914945429) 2024-03-21 03:41:32+00:00
FAIL [test-datalad (master)](https://github.com/datalad/git-annex/actions/runs/8369275314/job/22914945554) 2024-03-21 03:41:31+00:00
PASS [test-annex (custom-config1, windows-2019)](https://github.com/datalad/git-annex/actions/runs/8369275314/job/22914945681) 2024-03-21 03:41:31+00:00
FAIL [test-datalad (maint)](https://github.com/datalad/git-annex/actions/runs/8369275314/job/22914945818) 2024-03-21 03:41:32+00:00
FAIL [test-datalad (release)](https://github.com/datalad/git-annex/actions/runs/8369275314/job/22914945946) 2024-03-21 03:41:32+00:00
Local Clients:

openmind7 #1457 [[download logs](https://github.com/datalad/git-annex-ci-client-jobs/suites/21948480915/artifacts/1345152165)] 2024-03-21 04:58:42+00:00

PASS git-annex-home
PASS git-annex-om2
ndoli #1457 [[download logs](https://github.com/datalad/git-annex-ci-client-jobs/suites/21948056092/artifacts/1345079445)] 2024-03-21 04:33:07+00:00

PASS git-annex-home
FAIL git-annex-tmp
smaug #1457 [[download logs](https://github.com/datalad/git-annex-ci-client-jobs/suites/21947676965/artifacts/1345042780)] 2024-03-21 04:11:46+00:00

PASS git-annex
Appveyor Builds:

PASS [1.0.479](https://ci.appveyor.com/project/mih/git-annex/builds/49451108) 2024-03-21 07:03:06.188626+00:00

PASS [Environment: ID=WinP39core, APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2019, STACK_ROOT=c:\sr](https://ci.appveyor.com/project/mih/git-annex/builds/49451108/job/ygxey6r0s4gu2xpk)
PASS [Environment: ID=MacP38core, APPVEYOR_BUILD_WORKER_IMAGE=macos-monterey](https://ci.appveyor.com/project/mih/git-annex/builds/49451108/job/nj50tspcy9r9tmr4)

</details>

Need to be looked at.  @jwodder please have a look at typical causes and possibly relay anything related to @joeyh or address here please.

**Comment by jwodder** [comment]
@yarikoptic

* Going back just through the report sent on the 17th, all failures have been either when testing git-annex against DataLad or for the "git-annex-tmp" test on ndoli.

* For the report on the 21st, all DataLad tests failed, and it was for a variety of different reasons:
    * The Ubuntu tests all failed at the "Set up SSH target" step with "open /var/lib/docker/tmp/docker-import-602333103/repositories: no such file or directory".
    * The test suite failed on macOS and Windows due to an inability to connect to datalad-tests.datalad.org or store.datalad.org — aside from master on macOS, which failed before getting to the tests because a network error occurred when fetching the DataLad source from GitHub.

* For the other reports, most of the failing DataLad tests were only against a single source (master, maint, or release) per OS.  Most of the failures were due solely to the `datalad/core/distributed/tests/test_push.py::test_force_checkdatapresent` test failing.

* The CI runs last night (which will be reported in an e-mail later today) had no failures.

**Comment by yarikoptic** [comment]
THANK YOU @jwodder ... so need to look back at
- https://github.com/datalad/datalad/issues/7548
which I thought was solely due to change in git-annex due to subsec precision drop but I think it is not that

> The CI runs last night (which will be reported in an e-mail later today) had no failures.

It is always worth scaring things by complaining against them! ;)
