### ISSUE TITLE
stack-lts-18.13.yaml is no more for windows build

### ISSUE THREAD

**Issue by joeyh** [datalad/git-annex#204]
This file has been removed from git-annex and so you'll need to undo the change made earlier for 
https://github.com/datalad/git-annex/issues/168

Ie delete this line
https://github.com/datalad/git-annex/actions/runs/10137651923/workflow#L104

It should build fine now using stack.yaml

**Comment by yarikoptic** [comment]
sorry - missed/forgot this one. 

- https://github.com/datalad/git-annex/pull/210

is to see if all good before proceeding
