### ISSUE TITLE
"Update mirror" job broken

### ISSUE THREAD

**Issue by jwodder** [datalad/git-annex#206]
The last few runs of the "Update mirror" job have failed with "fatal: Could not read from remote repository."  We are using git://git.kitenet.net/git-annex as the remote URL, and [git-annex is still present on git.kitenet.net](https://git.kitenet.net/index.cgi/git-annex.git/), but the URL listed at the bottom of the page is git://git.joeyh.name/git-annex.git.

@yarikoptic Should we change the URL used by the job, or should we report this as an upstream problem?

**Comment by yarikoptic** [comment]
Oh, I missed that.
I thought that in general http "won over" as eg GitHub dropped it. But may be let's wait for a day to see what Joey says

**Comment by yarikoptic** [comment]
Joey fixed it up, was green for two days, release built today
