### ISSUE TITLE
Git-annex does not work with Git-Worktrees on crippled file systems (on Windows or Linux with a crippled file system)

### ISSUE THREAD

**Issue by christian-monch** [datalad/git-annex#211]
If, on a crippled file system, `git worktree add ...` is used to create a new worktree in a git repository with an annex, the annexed files are not available in the new worktree. They cannot be made available via `git annex get` either. Newly added worktrees contain a `.git`-file, instead of the link that `git-annex` creates on a non-crippled file system.

The following commands (Powershell on Windows) illustrate the problem (output of the commands is show as well):
```pwsh
> git init test-ds
Initialized empty Git repository in C:/tmp/test-ds/.git/
> cd test-ds
> git annex init
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.

  Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.

Switched to branch 'adjusted/master(unlocked)'
ok
(recording state in git...)
> write-output some_content > a.txt
> git annex add a.txt
add a.txt
ok
(recording state in git...)
> git commit -m "add an annexed file"
[adjusted/master(unlocked) a748a49] add an annexed file
 1 file changed, 1 insertion(+)
 create mode 100644 a.txt
> git worktree add wt-1
Preparing worktree (new branch 'wt-1')
HEAD is now at a748a49 add an annexed file
> cd wt-1
> cat .\a.txt
/annex/objects/SHA256E-s30--e32f901b2a52d0348cab2293d6aaa245ac8bad707c93bb06735f83d42c61ad91.txt
> git annex get a.txt
get a.txt (not available) 
  No other repository is known to contain the file.
failed
get: 1 failed
```

**Comment by yarikoptic** [comment]
bugs against git-annex should be filed/searched up at https://git-annex.branchable.com/ . E.g. of interest

- https://git-annex.branchable.com/tips/Using_git-worktree_with_annex/
- https://git-annex.branchable.com/bugs/git_init_fails_on_a_worktree_branch/

If you see anything which could be done in this repo (should we add additional testing or adjust build), please formulate that.

**Comment by christian-monch** [comment]
Thanks for the advice.
