### ISSUE TITLE
update-mirror workflow unable to push to GitHub

### ISSUE THREAD

**Issue by jwodder** [datalad/git-annex#32]
Starting earlier today, the update-mirror workflow has been unable to push new commits from upstream to this repository, failing with:

```
remote: Permission to datalad/git-annex.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/datalad/git-annex/': The requested URL returned error: 403
```

@yarikoptic Did you make any changes to the repository configuration recently?

**Comment by yarikoptic** [comment]
according to https://github.com/datalad/git-annex/actions?query=workflow%3A%22Update+mirror%22 started to happen 6 hours back, and the previous green which had pushed something was https://github.com/datalad/git-annex/runs/1555641566?check_suite_focus=true -- 10h ago.  I think I have done **nothing**, really nothing useful this early (6am'ish) in the morning today ;)  so must be something else what changed :-/

**Comment by jwodder** [comment]
The workflow is succeeding again.  I suspect it was a problem on GitHub's end.

**Comment by yarikoptic** [comment]
great
