### ISSUE TITLE
ENH: report build status from build- workflows back into PRs 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#34]
from a quick google hit https://tryexceptpass.org/article/continuous-builds-reporting-status/ it seems it should be quite easy to report status back to github on PRs.  So to avoid manually listing them like in https://github.com/datalad/git-annex/pull/33#issuecomment-746320124  I think a build for a PR triggered by `build-prs.yml` should POST back to github for the  target PR 
- upon initiation of the build that they are in progress
- upon completion of the build either they succeeded or failed

**Comment by jwodder** [comment]
Are you sure statuses are what you want?  Those just seem to attach to specific commits, as shown below, rather than to an entire PR.  They're rather out-of-the-way.

<img width="723" alt="Screen Shot 2020-12-16 at 11 50 57" src="https://user-images.githubusercontent.com/98207/102379690-1c281d00-3f95-11eb-854d-cb0d66684f59.png">

**Comment by yarikoptic** [comment]
as far as I understand, the overall PR status is just a status of the last commit in that PR, so indeed should work

**Comment by jwodder** [comment]
@yarikoptic You can currently see the "pending" statuses on a test PR at #36.

**Comment by yarikoptic** [comment]
it is beautiful! ;)

**Comment by yarikoptic** [comment]
although: although I reported "total satisfaction" too early ;-) 
- indeed PR is against the upstream/master so in principle it makes sense to report just right after git-annex build succeeded, but ideally:
  - could we report at two points:  success to build and then success to test datalad (in various incarnations)?
- also looking more carefully at https://github.com/datalad/git-annex/pull/35/files#diff-6aa85c651f1097357cd6e4ef95b9f37554fa7062a6661e05fabc61f2cb0d3e66R230 with my duplication allergy kicking in, I wonder if those `failure()` and `canceled()` could be just "folded" into a single step which would call `.github/workflows/tools/set-pr-status` with corresponding status?  if cannot be easily done, could be multiple steps just setting some variable (e.g. build-status) to be used in a single step which would call `.github/workflows/tools/set-pr-status`.   And then similar pattern used for reporting "datalad testing" at the end of that portion?

**Comment by jwodder** [comment]
@yarikoptic 

> could we report at two points: success to build and then success to test datalad (in various incarnations)?

That would involve a separate status for each test (including a separate status for each job instance in multijob matrices).

**Comment by jwodder** [comment]
@yarikoptic PR to compress the end-of-build steps: #38

**Comment by yarikoptic** [comment]
> That would involve a separate status for each test (including a separate status for each job instance in multijob matrices).

yes, but we would get a nice breakout and summary on how many canceled/skipped etc.  So should be similar to what we have in regular PRs like #38, or am I missing something?

**Comment by jwodder** [comment]
@yarikoptic PR to show statuses for every job: #39
