### ISSUE TITLE
Establish archival of build logs for (more) convenient access/analysis

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#43]
ATM it is somewhat painful to analyze them (what has failed in each of different OS runs etc).

https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts suggests that they could be "stored" as any other artifact, so may be there is even already some action helper to achieve that, if not -- we could either do some ad-hoc one within workflows, or even outside cron job to do that.  If per each run we get ~10 logs per OS, that would make it into just ~10k per year...  so we might want to establish a datalad super-dataset with logs archived per each year in separate subdatasets.  Not sure if should go into git (unlikely) -- probably into annex.

At some point the past I wrote quick&dirty script to fetch travis logs (http://www.onerussian.com/tmp/get-travis-buildlogs) which was a great help, but I never automated it to do it regularly/share with others in the project.

- relates to #2 - may be the same host/upload mechanism could be used
- eventually, if succesfull for github actions here (datalad/git-annex), we should adopt it also for datalad-extensions, and then expand to support other CIs (travis and appveyor).  That should be kept in mind while establishing this helper

attn @mih @kyleam @bpoldrack which might like to comment on/share their opinions/desires

**Comment by jwodder** [comment]
@yarikoptic 

* I believe that when that link refers to storing log files as artifacts, it's referring to files created directly by commands run within the workflow, not the GitHub Actions logs for the workflow as a whole.
* There do not appear to be any pre-existing facilities for saving GitHub Actions logs as artifacts.
* It appears that logs are not available via the API until after the respective workflow finishes, and so workflows cannot archive their own logs.  This leaves archival via cronjob as the only option.
* Where exactly do you want the logs stored: as artifacts of the cronjob, in a datalad dataset and/or Git repository, or elsewhere?

**Comment by yarikoptic** [comment]
I am thinking about a datalad dataset (but IMHO that should be "outside"), but overall it should be a helper which we run on cron (and possibly via `datalad run` which would take care about committing into whatever hierarchy it would be) which would fetch logs for all configured CIs (github actions, travis, appveyor are immediate targets) and place them into a consistent (and may be also configurable) hierarchy (modular/friendly to git/datalad), e.g. given configuration

```yaml
---
repo: https://github.com/datalad/datalad
ci:
  travis: true  # or full url?
  github: true
  appveyor: https://ci.appveyor.com/project/mih/datalad/
since: datestamp?
types: ['cron', 'PR']
layout: '{ci}/{year}/{month}/{type}/{type}/{type_id}/{build_id}/{step}.log'
```
where 
- `type_id` would "timedatestamp" for  `cron` and the "PR #" for `pr`.
- `step` if the log is split per steps, or just "all" if there is no splitting in a given `ci`

Helper should
- keep some record of what build logs it already fetched, so it avoids re-fetching them.
- would be nice if has options to specify explicitly which PR build to fetch (e.g. `--pr PR_NUMBER`) so we could use locally and not wait for cron 

Then datalad on top could be used to establish subdatasets e.g. per each `{year}` or any other level, and save all the changes where instructed (to git or git-annex).

**Comment by jwodder** [comment]
@yarikoptic 
* GitHub Actions (but not Travis and Appveyor, I believe) supports multiple workflows in a single repository; how should those be organized in the log layout?  Also, presumably there should be a configuration option for specifying which workflows to retrieve logs for?
* How should different matrix instances for a single job (e.g., Python 3.6 vs. Python 3.7) be organized?
* There can be multiple workflow runs for a single PR; how should those be organized?
* Should workflows run on pushes to `master` be supported?
* Something else to consider: The GitHub API provides workflow logs in the form of a zipfile whose contents are organized ... oddly.  For example, the contents of the log zip for [this workflow run](https://github.com/datalad/git-annex/actions/runs/467805073) are laid out as follows:

```
.
├── 1_build-package\ (1).txt
├── 1_build-package.txt
├── 1_test-annex\ (normal).txt
├── 1_test-annex-more.txt
├── 1_test-datalad\ (master).txt
├── 2_test-annex\ (crippled-tmp).txt
├── 2_test-annex.txt
├── 2_test-datalad\ (maint).txt
├── 3_test-annex\ (crippled-home).txt
├── 3_test-annex-more.txt
├── 3_test-datalad\ (release).txt
├── 4_test-annex\ (nfs-tmp).txt
├── 4_test-datalad.txt
├── build-package/
│   ├── 10_Import\ GPG\ keys.txt
│   ├── 11_Get\ the\ git-annex\ build\ environment\ container.txt
│   ├── 12_Build\ source\ packages.txt
│   ├── 13_Build\ binary\ package\ from\ the\ source\ package.txt
│   ├── 15_Upload\ packages.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 34_Post\ Checkout\ this\ repository.txt
│   ├── 35_Complete\ job.txt
│   ├── 4_Set\ up\ system.txt
│   ├── 5_Determine\ git-annex\ ref\ to\ build.txt
│   ├── 6_Check\ out\ source\ files.txt
│   ├── 7_Get\ build\ version.txt
│   ├── 8_Apply\ local\ patches.txt
│   └── 9_Adjust\ changelog\ generation\ script\ to\ use\ original\ branch.txt
├── test-annex\ (crippled-home)/
│   ├── 18_Post\ Checkout\ this\ repository.txt
│   ├── 19_Complete\ job.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 4_Download\ git-annex\ package.txt
│   ├── 5_Install\ git-annex\ package.txt
│   ├── 6_Print\ git-annex\ version.txt
│   └── 7_Run\ tests.txt
├── test-annex\ (crippled-tmp)/
│   ├── 18_Post\ Checkout\ this\ repository.txt
│   ├── 19_Complete\ job.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 4_Download\ git-annex\ package.txt
│   ├── 5_Install\ git-annex\ package.txt
│   ├── 6_Print\ git-annex\ version.txt
│   └── 7_Run\ tests.txt
├── test-annex\ (nfs-tmp)/
│   ├── 18_Post\ Checkout\ this\ repository.txt
│   ├── 19_Complete\ job.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 4_Download\ git-annex\ package.txt
│   ├── 5_Install\ git-annex\ package.txt
│   ├── 6_Print\ git-annex\ version.txt
│   └── 7_Run\ tests.txt
├── test-annex\ (normal)/
│   ├── 18_Post\ Checkout\ this\ repository.txt
│   ├── 19_Complete\ job.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 4_Download\ git-annex\ package.txt
│   ├── 5_Install\ git-annex\ package.txt
│   ├── 6_Print\ git-annex\ version.txt
│   └── 7_Run\ tests.txt
├── test-annex-more/
│   ├── 14_Post\ Checkout\ this\ repository.txt
│   ├── 15_Complete\ job.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 4_Download\ git-annex\ package.txt
│   ├── 5_Install\ git-annex\ package.txt
│   └── 6_Seek\ of\ dynlibs.txt
├── test-datalad\ (maint)/
│   ├── 10_Install\ nose\ et\ al\ (just\ in\ case!).txt
│   ├── 11_WTF!.txt
│   ├── 12_Run\ datalad\ tests.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 26_Post\ Checkout\ this\ repository.txt
│   ├── 27_Complete\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 4_Download\ git-annex\ package.txt
│   ├── 5_Install\ git-annex\ package.txt
│   ├── 6_Set\ up\ SSH\ target.txt
│   ├── 7_Set\ up\ environment.txt
│   ├── 8_Set\ up\ Python\ 3.7.txt
│   └── 9_Install\ maint\ Datalad.txt
├── test-datalad\ (master)/
│   ├── 10_Install\ nose\ et\ al\ (just\ in\ case!).txt
│   ├── 11_WTF!.txt
│   ├── 12_Run\ datalad\ tests.txt
│   ├── 1_Set\ up\ job.txt
│   ├── 26_Post\ Checkout\ this\ repository.txt
│   ├── 27_Complete\ job.txt
│   ├── 2_Checkout\ this\ repository.txt
│   ├── 4_Download\ git-annex\ package.txt
│   ├── 5_Install\ git-annex\ package.txt
│   ├── 6_Set\ up\ SSH\ target.txt
│   ├── 7_Set\ up\ environment.txt
│   ├── 8_Set\ up\ Python\ 3.7.txt
│   └── 9_Install\ master\ Datalad.txt
└── test-datalad\ (release)/
    ├── 10_Install\ nose\ et\ al\ (just\ in\ case!).txt
    ├── 11_WTF!.txt
    ├── 12_Run\ datalad\ tests.txt
    ├── 1_Set\ up\ job.txt
    ├── 26_Post\ Checkout\ this\ repository.txt
    ├── 27_Complete\ job.txt
    ├── 2_Checkout\ this\ repository.txt
    ├── 4_Download\ git-annex\ package.txt
    ├── 5_Install\ git-annex\ package.txt
    ├── 6_Set\ up\ SSH\ target.txt
    ├── 7_Set\ up\ environment.txt
    ├── 8_Set\ up\ Python\ 3.7.txt
    └── 9_Install\ release\ Datalad.txt
```

It appears that, for each job instance, the logs are available both as a directory containing one logfile per step and also as a single concatenated file.  Each job matrix (including those jobs with trivial matrices) also has a single logfile that just lists when each matrix instance started & stopped.  Note that, when a job matrix is trivial, it's not immediately obvious which file is for the job matrix and which is for the single instance.  (I have a guess for how they're organized, but I'd rather not rely on it.)

**Comment by yarikoptic** [comment]
> * Should workflows run on pushes to `master` be supported?

forgot about those -- yes, should probably be type "push" with `{type_id}` being probably `{branch}/{hexsha}` or ideally `{branch}/{git_describe}` where git_describe == the output from `git describe --always`.  Or do you see some other/better way to have something which would be sortable and easy to point to a specific commit?

> * GitHub Actions (but not Travis and Appveyor, I believe) supports multiple workflows in a single repository; how should those be organized in the log layout?  Also, presumably there should be a configuration option for specifying which workflows to retrieve logs for?
> * How should different matrix instances for a single job (e.g., Python 3.6 vs. Python 3.7) be organized?

excellent questions!  Overall, I think we should aim for something which would allow the "relate" to what we see in web interfaces of those platforms more easily.  Since seems to need to be CI specific, let's make path spec into  (swapped placement of `{ci}` since probably we should group them at that level)

`{year}/{month}/{type}/{type}/{ci}/{type_id}/{build}`

where `{build}` would be CI specific...:

In case of travis build like https://travis-ci.org/github/ReproNim/reproman/jobs/753067762, `{build_id}` == `1427` and `{step}` is those 1,2,3,4,5...  runs.  So `{build} == {build_id}/{step}`

appveyor:  seems to have `{build_id}` e.g. 1.0.5430 for https://ci.appveyor.com/project/mih/datalad/builds/37435610 but I do not observe any "{step}" id within listing there... may be there is some index within metadata?  if so - same here `{build} == {build_id}/{step}` 

github actions - they seems also have a number (e.g. 103 for https://github.com/datalad/git-annex/actions/runs/467805073) although  per each workflow, so I guess should be `{workflow}/{build_id}` (e.g. `Build git-annex on Ubuntu/103` for above) .  And if we are just to rely on the downloading the entire .zip, we do not really want `{step}` since it is pretty much provided "for free".  So here `{build} == {workflow}/{build_id}/` and then that directory would just contain extracted .zip


> * Something else to consider: The GitHub API provides workflow logs in the form of a zipfile whose contents are organized ... oddly.  For example, the contents of the log zip for [this workflow run](https://github.com/datalad/git-annex/actions/runs/467805073) are laid out as follows:
...
I would be just greedy and get them all as github provides

**Comment by jwodder** [comment]
@yarikoptic It appears that, for whatever reason, GitHub API requests for workflow runs triggered by pull request activity no longer include the PR information in the API response after the pull request is closed.  This makes getting the PR number for PR runs unreliable.

**Comment by yarikoptic** [comment]
> ... no longer ...

hm, that is odd, I wonder if it is an intentional change. Could you research more and even may be ask on https://support.github.com/ ?

**Comment by jwodder** [comment]
@yarikoptic I worded that poorly.  By "no longer," I meant that the workflow run object contains the PR data while the PR is open but does not contain it once the PR is closed.  I have no idea if this was always the case for the API or not.

**Comment by yarikoptic** [comment]
ah... that is still odd and IMHO worth asking since that is a valuable association even after PR is closed.  Do other CIs (appveyor, travis) provide such information after PR is closed? if so -- yet additional argument for github CI to provide and worth an support request or issue  if there is none yet

**Comment by jwodder** [comment]
I can confirm that the Travis API still reports the PR number for builds after the associated PR is closed.  I'm having trouble getting the Appveyor API to work at the moment, though.

**Comment by jwodder** [comment]
I've submitted a ticket to support.github.com about this.

**Comment by jwodder** [comment]
@yarikoptic I've written a first draft of a script for downloading GitHub Actions and Travis logs.  (For PR workflows with missing PR data, it just lists the PR number as "UNK".)  Where should I put it?  Since this will apparently be used for multiple projects, I'm guessing it'll get a repository of its own.  Will this be the same repository that all of the logs are stored in, or will those be separate somehow?

**Comment by yarikoptic** [comment]
Yeah, it is a generic tool. Let's put it under con/ organization. Have a name? Could be con/tineous following the precedent from @vsoch ;-)

**Comment by yarikoptic** [comment]
I also wonder (didn't look) if something in the logs themselves could point to the PR?

**Comment by jwodder** [comment]
@yarikoptic Currently, the script is just named `download-logs.py`.

> Could be con/tineous

Or rather con/tin**u**ous

> I also wonder (didn't look) if something in the logs themselves could point to the PR?

The logs themselves do not contain any data on what triggered them.

**Comment by yarikoptic** [comment]
oh hoh -- this is the issue which started it all! ;)
https://github.com/con/tinuous is there, and archive of builds and logs conveniently available on `smaug:/mnt/datasets/datalad/ci/git-annex` and for various other datalad and dandi projects around/elsewhere
