### ISSUE TITLE
setup testing of git-annex on "client" systems

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#57]
One immediate (and postponed for too long) use case is our HPC discovery with fancy lustre filesystem(s) of varying kinds mounted over NFS.  It had tripped git-annex before, and also due to use of ACL annex treats those as "crippled" which makes the experience "windows grade" with all the adjusted branches etc.

@joeyh is aware of ACL troubles, and have outlined a possible way forward in https://git-annex.branchable.com/todo/lockdown_hooks/ .  

Before that we better ensure that no other `git-annex` issues resurface on such (or may be other similar) deployments.

I do not think it would be possible or wise to try to establish "github actions workers" on those systems, so we need to come up with some alternative solution.  Without priming with my wild ad-hoc ideas, I wonder if you @jwodder see some nice way forward so we could trigger (e.g. on CRON) test jobs on client systems by downloading/extracting built git-annex .deb artifacts (that is how I did in the past) and running git-annex (and possibly later datalad) tests against these fresh builds on those systems.

**Comment by jwodder** [comment]
@yarikoptic If your goal is to run this via GitHub Actions, my idea would be to write all the steps in a shell script and then have the workflow SCP it over to the client and run it via SSH.

The one thing I'm wondering about is how you'd install and uninstall the .deb package on the client, as I assume users don't have permission to install software.  [I found some workarounds](https://askubuntu.com/a/350/25560), but I don't know how they'd work with git-annex.

**Comment by yarikoptic** [comment]
> @yarikoptic If your goal is to run this via GitHub Actions, my idea would be to write all the steps in a shell script and then have the workflow SCP it over to the client and run it via SSH.

Unfortunately this would be impossible (without heavily compromising security) e.g. for dartmouth HPC which is behind 2FA if accessing from outside (ok - could jump through e.g. smaug) and not allowing ssh keys authentication (kerberos -- would need password entry), etc.  So it should be of a "pull" relationship here.  
so one of my wild ideas was: May be "client" could query some beacon URL (e.g. on our server reachable via http) from time to time (every 5 minutes?), which if created would announce the URL for the annex .deb to download/test and then upload result (exit status, logs) to some other location . So - workflow would place the beacon online, and wait for results to appear at the expected target location (timing out with error at eg 60 minutes), and then analyze the status and cat the logs (or may be to avoid some leakage of some kind, we just upload the status and path to the logs for the build so if needed could be accessed)

> The one thing I'm wondering about is how you'd install and uninstall the .deb package on the client, as I assume users don't have permission to install software. [I found some workarounds](https://askubuntu.com/a/350/25560), but I don't know how they'd work with git-annex

oh, sorry I was not descriptive enough.  It would need to be extracted from .deb (I think it is an `ar` archive -- containing tarballs) and adjust PATH to point to that extracted `/usr/lib/git-annex` so that `git-annex` and `git` become the ones used.  That is how I tested it on discovery in the past (and it is a centos system... seemed to work)

**Comment by yarikoptic** [comment]
stroke me -- we can avoid using custom http server and have a dedicated `git-annex-ci-clients` git repo (better to not torture this one) through which to establish such "communication" (with dedicated ssh deploy keys), e.g. by creating a branch `build-<clientid>-<buildid>` (disconnected from the `master`) with needed information to request the build, which client would remove after fetching,  and then wait for `result-<clientid>-<buildid>` branch to appear with the result status, which workflow also would remove upon fetching ;-)  
we could even push built .deb through the `build-<clientid>-<buildid>` branch and rely on github to just GC those objects later since branches will be gone.

**Comment by yarikoptic** [comment]
another aspect: we could reuse a gpg key we already have and sign such request commit with it so clients could have extra assurance of having a "legit" request and workload to test.

**Comment by yarikoptic** [comment]
> The one thing I'm wondering about is how you'd install and uninstall the .deb package on the client, as I assume users don't have permission to install software. [I found some workarounds](https://askubuntu.com/a/350/25560), but I don't know how they'd work with git-annex.

I think we figured that out in `datalad-installer` for Linux (ar + tar IIRC), for OSX I am not sure how to "deploy" dmg without system wide installation, similarly on windows -- not sure.  My main target deployments will be Linux'es so let's concentrate on them.

I am thinking 

- a script (bash or basic python without major depends) which we could run on cron on any system
- each "deployment" gets it own permanent human friendly ID (e.g. "discovery-1") set in some config file or just env var
- script installs (in a temp location) fresh git-annex build, runs tests, submits result "here" for that ID + version of git-annex to be included in the dashboard somehow (yet to be figured out).  Dashboard should display the latest build annex version/result. 

`smaug` could be our sample deployment location (under `datalad` user)

**Comment by jwodder** [comment]
@yarikoptic 

> `buildid` probably should contain a datetime stamp (or git annex'es git-described sortable semver?) to allow for sorting/taking latest one if multiple detected

I was assuming that `buildid` would be the run number of the "Build git-annex on Ubuntu" workflow run that produced the original `.deb`, so they should already be sortable in a reasonable order.

> verify that you have write access to `/dartfs/rc/lab/D/DBIC/DBIC/archive/tmp`

Verified.

**Comment by yarikoptic** [comment]
@mih @aqw - do you feel wanting to join this effort of having git-annex (and may be datalad) regularly tested on your systems as part of the datalad/git-annex build setup?  if so, might want to checkout [our idea](https://github.com/datalad/git-annex/issues/57#issuecomment-1035036069) on such a possible setup -- may be you would see a shortcoming or something to improve.

**Comment by yarikoptic** [comment]
> * What do you want the cronjob to do if there are multiple `build-<clientid>-<buildid>` branches for the client ID?  Should all but the most recent be deleted?

ideally -- handle all.  Information on either build failed or ok for specific buildid on a given clienid could be useful.

> * Exactly what should be saved in `result-<clientid>-<buildid>` branches?

First we would start with just a simple `git annex test` testing output.  Later we would want to add testing of datalad similarly to what we do here in CI.  For each of those "test runs" we would need

- exit/status (0 vs not -- failed)
- log file (could be multiplexed stdout/stderr or may be better two separate?)

and related:

> * When `git annex test` is actually run on ndoli, should `TMPDIR` or `HOME` or something else be set to the value of that directory path you gave?

ideally we would like to add parametrizations (per client) for various runs. E.g. on `ndoli` I first would like to ensure that git-annex works correct in "stock" setup while invoked somewhere in `HOME` and also in some other locations.  So, it would be nice to provision a basic (we don't need full blown matrix support) way to parametrize test setups. May be could be smth like

```yaml
ndoli:
  test-annex:
    envs:
    - name: under-home
      cwd: ~/git-annex-ci/{buildid}
    - name: under-archive
      cwd: /dartfs/rc/lab/D/DBIC/DBIC/archive/tmp/{buildid}
      env:
         TMPDIR: /tmp/...  # in case we would like to overload it
    run: git annex test
  test-datalad:
    - name: datalad[master]
      env:
        DATALAD_COMMITTISH: master
    run: ci/some-test-datalad.sh
```
or may be `cwd` should be just `cwd-top` and each job would create some random subdir there?

> * I don't think con/tinuous should actually be involved for archiving logs; that sort of thing seems out of scope for it. My best idea for what to do instead is to set up a cronjob on smaug that pulls result-* branches and stores the contents somewhere.

Let's think about it more... after all we could consider this setup to be a "datalad-git-annex-ci" we would add support for in con/tinuous and thus making it all "uniform" somewhat.

**Comment by jwodder** [comment]
@yarikoptic It's possible for a workflow build number to be reused if a failed workflow run is attempted again; how should this be handled?  Should the build-ubuntu workflow just not create a `build-<clientid>-<buildid>` branch if one by that name already exists?

**Comment by jwodder** [comment]
@yarikoptic For parametrizing tests: How about each client has a directory of shell scripts, each one defining a test (consisting of envvar assignments and test commands to run)?  The cronjob then runs each script, saves the combined stdout & stderr to `{script-name}.log`, and saves the exit status to `{script-name}.rc`.  The badge generation code for the dashboard could then generate a separate status badge for each script of each client — though that would mean that the generation of the badge table in the README would need to be aware of all scripts on all clients.

**Comment by yarikoptic** [comment]
> @yarikoptic It's possible for a workflow build number to be reused if a failed workflow run is attempted again; how should this be handled? Should the build-ubuntu workflow just not create a `build-<clientid>-<buildid>` branch if one by that name already exists?

yeah, I guess, what else could we do? ;)   I guess there might be some "ambiguity" in such restarted cases but I guess those are rare if ever happening.

> For parametrizing tests: How about each client has a directory of shell scripts, each one defining a test (consisting of envvar assignments and test commands to run)? ...

On one hand - I like that idea since gives maximal desired flexibility.  I dislike that "configuration" is then gets spread out across multiple files, and cannot be contained in a single file, but may be we should just "embrace" that fully and have `clients/` directory with subdirectories per each `{clientid}/` which would have `tests/` which would have collection of `{scripts}` (may be keep needing `test_` prefix or such, skipping the rest so they could easily reuse some common functionality stored in non `test_` files)?  if some configuration per client would be needed we could have `{clientid}/config.yaml`

**Comment by jwodder** [comment]
@yarikoptic

> may be we should just "embrace" that fully and have `clients/` directory

So you want all of the configuration for all of the clients to be stored in some repository?  Would there be any specific procedure for deploying to clients/keeping the repository and clients in sync (e.g., should clients pull the repository before running the tests)?

> if some configuration per client would be needed we could have `{clientid}/config.yaml`

Currently, the only client configuration needed is the client ID, the location of the test scripts, and the directory in which to clone the `git-annex-ci-clients` repository.  At the moment, the cronjob script is written in bash and sources these details from a `.sh` config file, but I'm considering rewriting it in Python and having the configuration passed as arguments on the command line.

If I do rewrite it in Python, we could just store all of the test scripts as multiline strings in a single YAML file that covers all clients, e.g.:

```yaml
client-id-01:
  tests:
    annex: |
      TMPDIR=...
      cd /dartfs/rc/lab/D/DBIC/DBIC/archive/tmp/
      mkdir -p "$BUILDNO"
      cd "$BUILDNO"
      git annex version
      timeout 1800 git annex test
    datalad: |
      export DATALAD_COMMITTISH=master
      ci/some-test-datalad.sh
```

**Comment by jwodder** [comment]
@yarikoptic Idea for saving logs with con/tinuous: We can have the workflow that reacts to the creation of `result-*` branches by creating/updating badges also convert the logs into GitHub Actions artifacts (and then delete the `result-*` branch), and these artifacts can then be downloaded by con/tinuous.
