### ISSUE TITLE
libmagic builds not available

### ISSUE THREAD

**Issue by jwodder** [datalad/git-annex#66]
The Windows build of git-annex requires an artifact from [datalad/file-windows](https://github.com/datalad/file-windows).  However, datalad/file-windows went 60 days without any changes, and so its scheduled job for building the artifact was disabled three months ago.  Moreover, it appears that the API endpoint used to retrieve workflow run data only returns runs within about the last 90 days; as a result, when the Windows build of git-annex tries to look up the latest run, it's finding no data, and so the build fails.

@yarikoptic Please re-enable workflow runs for datalad/file-windows and do something to trigger a new build.  Also, in the future, GitHub should send you an e-mail whenever a scheduled workflow run is about to be disabled due to inactivity; you then need to view the run listing for that workflow and click the button to keep running the scheduled job.

**Comment by yarikoptic** [comment]
THANK YOU for the issue!
- added you as admin for that repo
- [ ] we need to setup tinuous for it (use-case didn't wait too long to come ;))
- [ ] switch to use that tinuous archive (probably from datasets.datalad.org)
- do not see anything to re-enable
- committed/pushed dummy 937b485ccc747c6ea81163c49724dd72501b6c11 , workflow seems to be running now: https://github.com/datalad/file-windows/actions/runs/968110378 . will update /close this issue upon completion

**Comment by yarikoptic** [comment]
it completed and artifact is there.  I guess lets either trigger or just wait for a build to happen here and see if situation is mitigated.  Let's close after we address those checkpoints?

**Comment by jwodder** [comment]
@yarikoptic Where exactly should I set up tinuous?

**Comment by yarikoptic** [comment]
I set up the ones for datalad and git-annex under `datalad@smaug:/mnt/datasets/datalad/ci$` -- you should be able to login as `datalad` now... Check setup cron jobs and do similar setup for this one.  I will later establish re-distribution via datasets.datalad.org .

**Comment by jwodder** [comment]
@yarikoptic tinuous and cron job set up.

**Comment by yarikoptic** [comment]
WONDERFUL! Thank you @jwodder.  Wouldn't we need some kind of a symlink (or file with information where to go to) to the most recent build so we could then tuneup workflow to use that?

**Comment by jwodder** [comment]
@yarikoptic I was thinking we could just glob all appropriate artifact directories and select the one with the highest date & build number.  (I was planning on doing the latter step using `sort`, but now that I look at the options, that might be a little tricky.)

**Comment by yarikoptic** [comment]
may be some feature we could/should add to con/tinuous itself? it knows the "latest" build.  Thanks to annex, we could even just duplicate the same file(s) in multiple location (to avoid symlink if not desired) and just also add some side car file with information about what is latest .  E.g. @joeyh wants/uses `dist/build-version` within https://datasets.datalad.org/?dir=/datalad/packages/windows (ATM not autoupdated thus outdated, I am yet to switch to use tinuous-produced one)

**Comment by jwodder** [comment]
@yarikoptic

> may be some feature we could/should add to con/tinuous itself?

I don't see a need for that at this time.

**Comment by yarikoptic** [comment]
IIRC we mitigated this
