### ISSUE TITLE
linux: make it build with newer git (currently 2.24.0)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#88]
I guess that is what `ubuntu-latest` has and thus it gets bundled within git-annex standalone package build.  Spotted while seeing fails of tests in https://github.com/datalad/datalad-extensions/runs/3751357707?check_suite_focus=true against "latest and greatest git-annex" that `git init` lacked `-b` option (to initialize into the named branch).

Even Debian stable (https://packages.debian.org/search?keywords=git) has 2.30.2-1 .

**Comment by jwodder** [comment]
@yarikoptic I suspect this is due to the singularity image (shub://datalad/datalad-extensions:buildenv-git-annex-buster) used to build git-annex for Linux being out of date.  Note that the `-b` option to `git init` was introduced in Git 2.28.

**Comment by yarikoptic** [comment]
Oh, I forgot our kitchen here... Given that shub is now readonly I guess we need to establish some alternative build/deployment for that container...

**Comment by yarikoptic** [comment]
based on that https://github.com/datalad/datalad-extensions/blob/master/containers/Singularity.buildenv-git-annex-buster please setup building (github action, to react on changes to Dockerfile) and pushing to dockerhub.
- let's use Debian bullseye (current stable) and nd_freeze to some date in the near past
- push to `dataladtester/buildenv-git-annex-buster` and pull that one into singularity (worth first checking locally e.g. on smaug if would work as expected).  I have added `DOCKER_TOKEN` secret (I hope it has permissions, if not -- will adjust)

**Comment by yarikoptic** [comment]
No, it is a token (not password), likely for yarikoptic user. May be that one lacks permission... I will look into it shortly

**Comment by jwodder** [comment]
@yarikoptic I don't see a way to use just a token with the Docker CLI.

**Comment by yarikoptic** [comment]
I think token should be used as password but likely yarikoptic has no authority to push to that organization... I will check

**Comment by yarikoptic** [comment]
uff... I can login (testing locally) with token just fine and when you generate a token it says 
![image](https://user-images.githubusercontent.com/39889/136039281-c4a8348c-81ad-4f3e-b83c-e7874f419db6.png)
(I have removed this one so should be safe).  But whenever I try to push anything even to my account or datalad organization (where I added us both as owners), it indeed fails:
```
(git-annex)lena:~datalad/ansi[master]
$> docker push yarikoptic/squeeze
Using default tag: latest
The push refers to repository [docker.io/yarikoptic/squeeze]
5f70bf18a086: Preparing 
085be35d9b38: Preparing 
denied: requested access to the resource is denied
(dev3) 1 18401 ->1 [1].....................................:Tue 05 Oct 2021 10:07:03 AM EDT:.
(git-annex)lena:~datalad/ansi[master]
$> docker tag debian:squeeze squeeze:latest           
(dev3) 1 18402 [1].....................................:Tue 05 Oct 2021 10:07:10 AM EDT:.
(git-annex)lena:~datalad/ansi[master]
$> docker push squeeze                     
Using default tag: latest
The push refers to repository [docker.io/library/squeeze]
5f70bf18a086: Preparing 
085be35d9b38: Preparing 
denied: requested access to the resource is denied
(dev3) 1 18403 ->1 [1].....................................:Tue 05 Oct 2021 10:07:14 AM EDT:.
(git-annex)lena:~datalad/ansi[master]
$> docker tag debian:squeeze datalad/squeeze:latest
(dev3) 1 18404 [1].....................................:Tue 05 Oct 2021 10:07:57 AM EDT:.
(git-annex)lena:~datalad/ansi[master]
$> docker push datalad/squeeze   
Using default tag: latest
The push refers to repository [docker.io/datalad/squeeze]
5f70bf18a086: Preparing 
085be35d9b38: Preparing 
denied: requested access to the resource is denied
```
uff...   as noted above, I have added you to datalad organization, so we might just push under that one.  Please try to figure it out
