### ISSUE TITLE
Add invocation of datalad's tools/ci/deploy_datalad-rootca on Ubuntu

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#97]
`master` branch of datalad now goes extra mile to enable testing for https urls, and requires running `tools/ci/deploy_datalad-rootca` script (has `sudo` inside already, not distributed with pip installed copy of datalad).  If that is not done -- test should gracefully skip.

I thought that adding call out to that script should resolve current build failure on ubuntu against master which I saw with some related errors (but now failing to find -- may be they were not that critical actual).
Recent build succeeded (https://github.com/datalad/git-annex/actions/runs/1649581476) so I guess it was not the issue exactly, and there is no urgency to have this done , but we better have those tests enabled here on CI.

Note: that script will not be present in `maint` branch but setting it using code/version from `master` branch (i.e. not bother doing it only for `master` and then needing to add later after 0.16.0 release for everything else) of datalad should not have negative effects AFAIK on tests against release/`maint`, but I could be proven wrong.

**Comment by jwodder** [comment]
@yarikoptic The script in question requires a file from `datalad/tests/ca/`, but this directory is not included when datalad is installed.  [I mentioned this before](https://github.com/datalad/datalad/pull/6273#issuecomment-990990930); should it be installed?

**Comment by yarikoptic** [comment]
Just shallow clone entire datalad repo to get all files?

Please submit a separate PR with the fix for shipping those needed files.

**Comment by jwodder** [comment]
@yarikoptic PR submitted: https://github.com/datalad/datalad/pull/6336
