### ISSUE TITLE
Add a test run on macos-latest to compliment #96

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#98]
I think we should proceed with #96 BUT we need to ensure that `git-annex` is usable on OSX 11 and above.

For that I think that OSX workflow should be adjusted to include at least a single run (no matrix for different TMPFS setups etc) of `git annex test` on `macos-latest`.

Ideally should be done as a part of #96 but could be done separately later -- if we discover that `git-annex` build done on osx 10 is not usable on 11 -- we would be doomed to provide multiple builds I guess, or check @joeyh 's [idea](https://github.com/datalad/git-annex/issues/95#issuecomment-1004228770) of not bundling dynamic libraries in dmg

**Comment by joeyh** [comment]
Alternatively, a test on maxos-previous, if that exists.

**Comment by jwodder** [comment]
Done as part of #96.
